/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.http.HttpResponse;
import org.apache.http.NameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.params.HttpParams;
import org.apache.http.util.EntityUtils;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author adityadhall
 */
public class main_win extends javax.swing.JFrame {
    
    
    private static String Cat_url ="http://10.21.1.227:8080/MechAms/CategoryServlet";
    private static String Prod_url="http://10.21.1.227:8080/MechAms/ProductServlet";
//incomplete
    /**
     * Creates new form main_win
     */
    
    public main_win() {
        initComponents();
        
        initialiseMain();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddItem = new javax.swing.JButton();
        Display = new javax.swing.JButton();
        Level1Panel = new javax.swing.JPanel();
        SelectOrAddItemTypePanel = new javax.swing.JPanel();
        selectItemType_text = new javax.swing.JLabel();
        selectItemType_box = new javax.swing.JComboBox<>();
        addNewItemType_button = new javax.swing.JButton();
        addNewItemType_text = new javax.swing.JLabel();
        or_text = new javax.swing.JLabel();
        Level2Panel = new javax.swing.JPanel();
        AddItemPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addItemTable = new javax.swing.JTable();
        selectAttr_box = new javax.swing.JComboBox<>();
        attrValue = new javax.swing.JTextField();
        addAttrValue_button = new javax.swing.JButton();
        confirmAddItem_button = new javax.swing.JButton();
        selectAttr_text = new javax.swing.JLabel();
        AddNewItemTypePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addNewItemTypeTable = new javax.swing.JTable();
        newType = new javax.swing.JTextField();
        attrName_text = new javax.swing.JLabel();
        itemType_text = new javax.swing.JLabel();
        attrName = new javax.swing.JTextField();
        addAttr_button = new javax.swing.JButton();
        confirmAddItemType_button = new javax.swing.JButton();
        DisplayItemTypePanel = new javax.swing.JPanel();
        selectItemType_text_display = new javax.swing.JLabel();
        selectItemType_box_display = new javax.swing.JComboBox<>();
        deleteSelected_button_display = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayItemTypeTable = new javax.swing.JTable();
        TopMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(400, 400));

        AddItem.setText("Add Item");
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });

        Display.setText("Display");
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        Level1Panel.setLayout(new java.awt.CardLayout());

        selectItemType_text.setText("Select Item Type");

        selectItemType_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectItemType_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectItemType_boxItemStateChanged(evt);
            }
        });
        selectItemType_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectItemType_boxActionPerformed(evt);
            }
        });

        addNewItemType_button.setText("Add New Item Type");
        addNewItemType_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewItemType_buttonActionPerformed(evt);
            }
        });

        addNewItemType_text.setText("Add New Item Type First");

        or_text.setText("OR");

        Level2Panel.setLayout(new java.awt.CardLayout());

        addItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        addItemTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        addItemTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(addItemTable);

        selectAttr_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectAttr_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAttr_boxActionPerformed(evt);
            }
        });

        addAttrValue_button.setText("Add");
        addAttrValue_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAttrValue_buttonActionPerformed(evt);
            }
        });

        confirmAddItem_button.setText("Confirm");
        confirmAddItem_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddItem_buttonActionPerformed(evt);
            }
        });

        selectAttr_text.setText("Select Attribute");

        javax.swing.GroupLayout AddItemPanelLayout = new javax.swing.GroupLayout(AddItemPanel);
        AddItemPanel.setLayout(AddItemPanelLayout);
        AddItemPanelLayout.setHorizontalGroup(
            AddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddItemPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(AddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmAddItem_button)
                    .addGroup(AddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(selectAttr_text)
                        .addGroup(AddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddItemPanelLayout.createSequentialGroup()
                                .addComponent(selectAttr_box, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(attrValue, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addAttrValue_button)))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        AddItemPanelLayout.setVerticalGroup(
            AddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddItemPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(selectAttr_text, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAttr_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attrValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAttrValue_button))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(confirmAddItem_button)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        Level2Panel.add(AddItemPanel, "card3");

        addNewItemTypeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        addNewItemTypeTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(addNewItemTypeTable);

        newType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTypeActionPerformed(evt);
            }
        });

        attrName_text.setText("Attribute Name");

        itemType_text.setText("Item Type");

        attrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attrNameActionPerformed(evt);
            }
        });

        addAttr_button.setText("Add Attribute");
        addAttr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAttr_buttonActionPerformed(evt);
            }
        });

        confirmAddItemType_button.setText("Confirm");
        confirmAddItemType_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddItemType_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddNewItemTypePanelLayout = new javax.swing.GroupLayout(AddNewItemTypePanel);
        AddNewItemTypePanel.setLayout(AddNewItemTypePanelLayout);
        AddNewItemTypePanelLayout.setHorizontalGroup(
            AddNewItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewItemTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddNewItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddNewItemTypePanelLayout.createSequentialGroup()
                        .addGroup(AddNewItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemType_text)
                            .addComponent(attrName_text))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddNewItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddNewItemTypePanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(newType, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(attrName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addAttr_button)
                        .addGap(201, 201, 201))
                    .addGroup(AddNewItemTypePanelLayout.createSequentialGroup()
                        .addGroup(AddNewItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confirmAddItemType_button)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        AddNewItemTypePanelLayout.setVerticalGroup(
            AddNewItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddNewItemTypePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AddNewItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemType_text)
                    .addComponent(newType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(AddNewItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attrName_text)
                    .addComponent(attrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAttr_button))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmAddItemType_button)
                .addGap(9, 9, 9))
        );

        Level2Panel.add(AddNewItemTypePanel, "card2");

        javax.swing.GroupLayout SelectOrAddItemTypePanelLayout = new javax.swing.GroupLayout(SelectOrAddItemTypePanel);
        SelectOrAddItemTypePanel.setLayout(SelectOrAddItemTypePanelLayout);
        SelectOrAddItemTypePanelLayout.setHorizontalGroup(
            SelectOrAddItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectOrAddItemTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectOrAddItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectItemType_text, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectItemType_box, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(or_text)
                .addGap(38, 38, 38)
                .addGroup(SelectOrAddItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewItemType_text)
                    .addComponent(addNewItemType_button))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(SelectOrAddItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SelectOrAddItemTypePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Level2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        SelectOrAddItemTypePanelLayout.setVerticalGroup(
            SelectOrAddItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectOrAddItemTypePanelLayout.createSequentialGroup()
                .addGroup(SelectOrAddItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectOrAddItemTypePanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(SelectOrAddItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addNewItemType_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectItemType_text))
                        .addGap(7, 7, 7)
                        .addGroup(SelectOrAddItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectItemType_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewItemType_button)))
                    .addGroup(SelectOrAddItemTypePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(or_text, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(446, Short.MAX_VALUE))
            .addGroup(SelectOrAddItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SelectOrAddItemTypePanelLayout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(Level2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Level1Panel.add(SelectOrAddItemTypePanel, "card2");

        selectItemType_text_display.setText("Select Item Type");

        selectItemType_box_display.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectItemType_box_display.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectItemType_box_displayItemStateChanged(evt);
            }
        });
        selectItemType_box_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectItemType_box_displayActionPerformed(evt);
            }
        });

        deleteSelected_button_display.setText("Delete Selected");
        deleteSelected_button_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelected_button_displayActionPerformed(evt);
            }
        });

        displayItemTypeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        displayItemTypeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        displayItemTypeTable.getTableHeader().setReorderingAllowed(false);
        displayItemTypeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayItemTypeTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(displayItemTypeTable);

        javax.swing.GroupLayout DisplayItemTypePanelLayout = new javax.swing.GroupLayout(DisplayItemTypePanel);
        DisplayItemTypePanel.setLayout(DisplayItemTypePanelLayout);
        DisplayItemTypePanelLayout.setHorizontalGroup(
            DisplayItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayItemTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DisplayItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectItemType_text_display, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DisplayItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3)
                        .addGroup(DisplayItemTypePanelLayout.createSequentialGroup()
                            .addComponent(selectItemType_box_display, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(87, 87, 87)
                            .addComponent(deleteSelected_button_display))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        DisplayItemTypePanelLayout.setVerticalGroup(
            DisplayItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayItemTypePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(selectItemType_text_display)
                .addGap(22, 22, 22)
                .addGroup(DisplayItemTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectItemType_box_display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSelected_button_display))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        Level1Panel.add(DisplayItemTypePanel, "card2");

        jMenu1.setText("File");
        TopMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        TopMenuBar.add(jMenu2);

        setJMenuBar(TopMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Display, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(AddItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(Level1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Level1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Display)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialiseMain(){
    //      String[] categories = { "Football", "Cricket", "Maut ka Khel" };
        
        String[] categories =null;
        try(CloseableHttpClient httpclient = HttpClientBuilder.create().build())
        {
            HttpPost request= new HttpPost(Cat_url);
            List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>(1);
            nameValuePairs.add(new BasicNameValuePair("type",
                    "enquiry"));
            request.setEntity(new UrlEncodedFormEntity(nameValuePairs));
            HttpResponse response = httpclient.execute(request);            
            String result = EntityUtils.toString(response.getEntity(),"UTF-8");
            try
            {
                JSONParser parser =new JSONParser();
                Object resultObject = parser.parse(result);
                JSONObject obj = (JSONObject)resultObject;
                if(obj.get("type").toString().equals("category"))
                {
                    int num_category = Integer.valueOf(obj.get("no_category").toString());
                    if (num_category != 0)
                    {
                        categories =new String[num_category];
                        for(int count = 1;count<=num_category;count++)
                        {
                            categories[count-1] = obj.get("category_"+Integer.toString(count)).toString();
                        }
                    }   
                }
            }catch(Exception e){
            }
            
        }catch(Exception ex)
        {
        }
        if(categories != null)
            PopulateItemTypeList( categories );
        else
        {String[] no_item ={"no_items"};
            PopulateItemTypeList(no_item);}            
        
        //Setting table attributes as per selected item type
        SettingItemTypeListener();
        DisplayItemTypeListener();
 
        
    }
    
    
    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed
        // TODO add your handling code here:
        
        //remove Level1Panel
        Level1Panel.removeAll();
        Level1Panel.repaint();
        Level1Panel.revalidate();
        
        //adding SelectOrAddItemTypePanel
        Level1Panel.add(SelectOrAddItemTypePanel);
        Level1Panel.repaint();
        Level1Panel.revalidate();
    }//GEN-LAST:event_AddItemActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
        
        //remove Level1Panel
        Level1Panel.removeAll();
        Level1Panel.repaint();
        Level1Panel.revalidate();
        
        //adding DisplayItemTypePanel
        Level1Panel.add(DisplayItemTypePanel);
        Level1Panel.repaint();
        Level1Panel.revalidate();
    }//GEN-LAST:event_DisplayActionPerformed

    private void deleteSelected_button_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelected_button_displayActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) displayItemTypeTable.getModel();
        
        String tableName = selectItemType_box_display.getSelectedItem().toString();
        String idNo = tableModel.getValueAt( displayItemTypeTable.getSelectedRow(), 0 ).toString();
        //Send the 'idNo' to be deleted from the selected table in DB
        //Apna delete ka code yaha dalo
        try(CloseableHttpClient httpclient = HttpClientBuilder.create().build())
        {
            HttpPost request= new HttpPost(Prod_url);
            List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>(1);
            nameValuePairs.add(new BasicNameValuePair("type","delete"));
            nameValuePairs.add(new BasicNameValuePair("table_name",tableName));
            nameValuePairs.add(new BasicNameValuePair("id",idNo));
            request.setEntity(new UrlEncodedFormEntity(nameValuePairs));
            HttpResponse response = httpclient.execute(request);            
            String result = EntityUtils.toString(response.getEntity(),"UTF-8");
        }catch(Exception ex)
        {
        }             
      
        String titleBar = "Selected row deleted from the table";
        String infoMsg = "Item Id = " + idNo + "\n" + "Item Type = " + tableName;
        JOptionPane.showMessageDialog( null, infoMsg, titleBar, JOptionPane.INFORMATION_MESSAGE );
        
        //Update the display table from the DB
        PopulateTable();
    }//GEN-LAST:event_deleteSelected_button_displayActionPerformed

    private void attrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attrNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attrNameActionPerformed

    private void newTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newTypeActionPerformed

    private void selectAttr_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAttr_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectAttr_boxActionPerformed

    private void selectItemType_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectItemType_boxActionPerformed
        Level2Panel.removeAll();
        Level2Panel.add( AddItemPanel );
        Level2Panel.repaint();
        Level2Panel.revalidate();
        
        DefaultTableModel tableModel = (DefaultTableModel) addNewItemTypeTable.getModel();
        tableModel.setColumnCount( 0 );
        newType.setText( "" );
        attrName.setText( "" );
    }//GEN-LAST:event_selectItemType_boxActionPerformed

    private void addAttrValue_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAttrValue_buttonActionPerformed
        int colNo = selectAttr_box.getSelectedIndex();
        
        DefaultTableModel tableModel = (DefaultTableModel) addItemTable.getModel();
        tableModel.setRowCount( 1 );
        tableModel.setValueAt( attrValue.getText(), 0, colNo );
        
        attrValue.setText("");
    }//GEN-LAST:event_addAttrValue_buttonActionPerformed

    private void selectItemType_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectItemType_boxItemStateChanged
        
    }//GEN-LAST:event_selectItemType_boxItemStateChanged

    private void confirmAddItem_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddItem_buttonActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) addItemTable.getModel();
        
        String attribute_name = "attribute_name_";
        String attribute_val = "attribute_val_";
        try(CloseableHttpClient httpclient = HttpClientBuilder.create().build())
        {
            HttpPost request= new HttpPost(Prod_url);
            List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>(1);
            nameValuePairs.add(new BasicNameValuePair("type","insert"));
            nameValuePairs.add(new BasicNameValuePair("table_name",selectItemType_box.getSelectedItem().toString()));
            nameValuePairs.add(new BasicNameValuePair("no_attributes",Integer.toString(tableModel.getColumnCount())));
            for(int i = 0; i < tableModel.getColumnCount();i++)
            {
                nameValuePairs.add(new BasicNameValuePair(attribute_name+Integer.toString(i+1),tableModel.getColumnName( i )));
                nameValuePairs.add(new BasicNameValuePair(attribute_val+Integer.toString(i+1),tableModel.getValueAt( 0, i ).toString()));                
            }
            request.setEntity(new UrlEncodedFormEntity(nameValuePairs));
            HttpResponse response = httpclient.execute(request);            
            String result = EntityUtils.toString(response.getEntity(),"UTF-8");
        }catch(Exception ex)
        {
        }        
        
        String titleBar = selectItemType_box.getSelectedItem().toString() + " - Item Added";
        //Use "infoMsg" to send query to add tuple to the table "selectItemType_box.getSelectedItem().toString()"
        String infoMsg = "";
        for( int i = 0; i < tableModel.getColumnCount(); i++ ){
            infoMsg += tableModel.getColumnName( i ) + " = " + tableModel.getValueAt( 0, i ).toString() + "\n";
        }
        JOptionPane.showMessageDialog( null, infoMsg, titleBar, JOptionPane.INFORMATION_MESSAGE );
        tableModel.setColumnCount( 0 );
    }//GEN-LAST:event_confirmAddItem_buttonActionPerformed

    private void addNewItemType_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewItemType_buttonActionPerformed
        Level2Panel.removeAll();
        Level2Panel.repaint();
        Level2Panel.revalidate();
        
        Level2Panel.add( AddNewItemTypePanel );
        Level2Panel.repaint();
        Level2Panel.revalidate();
    }//GEN-LAST:event_addNewItemType_buttonActionPerformed

    private void addAttr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAttr_buttonActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) addNewItemTypeTable.getModel();
        
        tableModel.addColumn( attrName.getText() );
        
        attrName.setText("");
    }//GEN-LAST:event_addAttr_buttonActionPerformed

    private void confirmAddItemType_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddItemType_buttonActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) addNewItemTypeTable.getModel();

        try(CloseableHttpClient httpclient = HttpClientBuilder.create().build())
        {
            HttpPost request= new HttpPost(Cat_url);
            List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>(1);
            nameValuePairs.add(new BasicNameValuePair("type","create"));
            nameValuePairs.add(new BasicNameValuePair("table_name",newType.getText()));
            nameValuePairs.add(new BasicNameValuePair("no_attributes",Integer.toString(tableModel.getColumnCount())));
            for(int i = 0; i < tableModel.getColumnCount();i++)
            {
                nameValuePairs.add(new BasicNameValuePair("attribute_name_"+Integer.toString(i+1),tableModel.getColumnName( i )));             
            }
            request.setEntity(new UrlEncodedFormEntity(nameValuePairs));
            HttpResponse response = httpclient.execute(request);            
            String result = EntityUtils.toString(response.getEntity(),"UTF-8");
        }catch(Exception ex)
        {
        }             
        String titleBar = newType.getText() + " - New Item Type Added";
        String infoMsg = "Created table " + newType.getText() + " with following attributes:\n";
        for( int i = 0; i < tableModel.getColumnCount(); i++ ){
            infoMsg += "\n" + tableModel.getColumnName( i );
        }
        //Make table in DB, with table name 'newType.getText().toString()' and columns 'tableModel.getColumnName( i ).toString()' for all i's
        JOptionPane.showMessageDialog( null, infoMsg, titleBar, JOptionPane.INFORMATION_MESSAGE );
        
        tableModel.setColumnCount( 0 );
        newType.setText( "" );
        attrName.setText( "" );
    }//GEN-LAST:event_confirmAddItemType_buttonActionPerformed
    
    @SuppressWarnings("empty-statement")
    private void PopulateTable(){
        DefaultComboBoxModel boxModel = (DefaultComboBoxModel) selectItemType_box_display.getModel();
        Object selected = boxModel.getSelectedItem();
        
        String[][] tuples = null;
        String[] attr_names = null;
        String[] temp;
        int count,count_h;
        try(CloseableHttpClient httpclient = HttpClientBuilder.create().build())
        {
            HttpPost request= new HttpPost(Prod_url);
            List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>(2);
            nameValuePairs.add(new BasicNameValuePair("type","enquiry"));
            nameValuePairs.add(new BasicNameValuePair("table_name", selected.toString()));
            request.setEntity(new UrlEncodedFormEntity(nameValuePairs));
            HttpResponse response = httpclient.execute(request);            
            String result = EntityUtils.toString(response.getEntity(),"UTF-8");
            try
            {
                JSONParser parser =new JSONParser();
                Object resultObject = parser.parse(result);
                JSONObject obj = (JSONObject)resultObject;
                int tuple_count = Integer.valueOf(obj.get("count").toString());
                int attr_count = Integer.valueOf(obj.get("attr_count").toString());
                tuples = new String[tuple_count][attr_count]; 
                attr_names = new String[attr_count];
                for (count = 1;count <= attr_count;count++)
                {
                    attr_names[count-1] = obj.get("attributes_"+Integer.toString(count)).toString();
                }
                for (count = 1;count <= tuple_count;count++)
                {
                    temp = obj.get("row_"+Integer.toString(count)).toString().split("-");
                    for (count_h = 0;count_h < attr_count;count_h++)
                    {
                        tuples[count-1][count_h] = temp[count_h];
                    }
                }
            }
            catch(Exception e){
            }
        }
        catch(Exception ex){
        }
        
        
        InitialiseColumns( displayItemTypeTable, attr_names );
        
        DefaultTableModel tableModel = (DefaultTableModel) displayItemTypeTable.getModel();
        tableModel.setRowCount( 0 );
        
        //Get total no. of tuples in the given table from the DB
        
        //Get 2-D tuples from DB
        
        for( String[] tuple: tuples ){
            //Extract each tuple one-by-one
            //tuple = allTuples[ 2 ];
            //tuple = { Integer.toString( i ), "Data1", "Data2", "Data3" }; Doesn't work
            
            tableModel.addRow( tuple );
        }
    }
    
    private void selectItemType_box_displayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectItemType_box_displayItemStateChanged
        
    }//GEN-LAST:event_selectItemType_box_displayItemStateChanged

    private void selectItemType_box_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectItemType_box_displayActionPerformed
        
    }//GEN-LAST:event_selectItemType_box_displayActionPerformed

    private void displayItemTypeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayItemTypeTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_displayItemTypeTableMouseClicked
    
    
    //Handling drop down box
    private void PopulateItemTypeList( String[] itemTypeList ){ 
        selectItemType_box.setModel( new DefaultComboBoxModel( itemTypeList ) );
        selectItemType_box_display.setModel( new DefaultComboBoxModel( itemTypeList ) );
    }
    
    private void PopulateAttrList( String[] attrList ){ 
        selectAttr_box.setModel( new DefaultComboBoxModel( attrList ) );
    }
    
    //Initiating the columns of the table
    private void InitialiseColumns( JTable table, String[] attrList ){
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        
        tableModel.setColumnCount( 0 );
        
        for( String attr: attrList ){
            tableModel.addColumn( attr );
        }
    }
    
    private void SettingItemTypeListener(){
        selectItemType_box.addActionListener( new ActionListener(){
            public void actionPerformed( ActionEvent event ){
                JComboBox box = (JComboBox) event.getSource();
                Object selected = box.getSelectedItem();
                String[] attrList =null;
                try(CloseableHttpClient httpclient = HttpClientBuilder.create().build())
                {
                    HttpPost request= new HttpPost(Prod_url);
                    List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>(2);
                    nameValuePairs.add(new BasicNameValuePair("type","describe"));
                    nameValuePairs.add(new BasicNameValuePair("table_name", selected.toString()));
                    request.setEntity(new UrlEncodedFormEntity(nameValuePairs));
                    HttpResponse response = httpclient.execute(request);            
                    String result = EntityUtils.toString(response.getEntity(),"UTF-8");
                    try
                    {
                        JSONParser parser =new JSONParser();
                        Object resultObject = parser.parse(result);
                        JSONObject obj = (JSONObject)resultObject;
                        if(obj.get("type").toString().equals("attributes"))
                        {
                            int num_category = Integer.valueOf(obj.get("no_attributes").toString());
                            if (num_category != 0)
                            {
                                attrList =new String[num_category];
                                for(int count = 1;count<=num_category;count++)
                                {
                                    attrList[count-1] = obj.get("attributes_"+Integer.toString(count)).toString();
                                }
                            }   
                        }
                    }catch(Exception e){
                    }

                }catch(Exception ex)
                {
                }
                if( attrList == null){
                    String[] no_Attr = { "noAttributes" };
                    PopulateAttrList( no_Attr );
                    InitialiseColumns( addItemTable, attrList );

                }
                else{
                    String[] attrListWithoutId = new String[ attrList.length - 1 ];
                    for( int i = 0; i < attrList.length; i++ ){
                        if( i != 0 ){
                            attrListWithoutId[ i - 1 ] = attrList[ i ];
                        }
                    }
                    
                    PopulateAttrList( attrListWithoutId );
                    InitialiseColumns( addItemTable, attrListWithoutId );
                }

            }
        });
    }
    
    private void DisplayItemTypeListener(){
        selectItemType_box_display.addActionListener(new ActionListener(){
            public void actionPerformed( ActionEvent event ){
                //JComboBox box = (JComboBox) event.getSource();
                //Object selected = box.getSelectedItem();
                
                //Use { selected.toString() } to get the selected table from DB and display its columns as 'attrList' and data stored in the table in form of tuples
                
                PopulateTable();
                //if-else for testing - Remove if-else after DB access
/*                if( selected.toString().equals( "Football")){
                    //Get all column names of selected table
                    String[] attrList = { "Id", "Company Name", "Size", "Quantity", "Colour" };

                    InitialiseColumns( displayItemTypeTable, attrList ); 
                    PopulateTable();
                }
                else{
                    String[] attrList = {"Id", "Just", "Checking"};
                    InitialiseColumns( displayItemTypeTable, attrList );
                    PopulateTable();
                }
*/
            }
        });
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
     
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new main_win().setVisible(true);
                }
            
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItem;
    private javax.swing.JPanel AddItemPanel;
    private javax.swing.JPanel AddNewItemTypePanel;
    private javax.swing.JButton Display;
    private javax.swing.JPanel DisplayItemTypePanel;
    private javax.swing.JPanel Level1Panel;
    private javax.swing.JPanel Level2Panel;
    private javax.swing.JPanel SelectOrAddItemTypePanel;
    private javax.swing.JMenuBar TopMenuBar;
    private javax.swing.JButton addAttrValue_button;
    private javax.swing.JButton addAttr_button;
    private javax.swing.JTable addItemTable;
    private javax.swing.JTable addNewItemTypeTable;
    private javax.swing.JButton addNewItemType_button;
    private javax.swing.JLabel addNewItemType_text;
    private javax.swing.JTextField attrName;
    private javax.swing.JLabel attrName_text;
    private javax.swing.JTextField attrValue;
    private javax.swing.JButton confirmAddItemType_button;
    private javax.swing.JButton confirmAddItem_button;
    private javax.swing.JButton deleteSelected_button_display;
    private javax.swing.JTable displayItemTypeTable;
    private javax.swing.JLabel itemType_text;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField newType;
    private javax.swing.JLabel or_text;
    private javax.swing.JComboBox<String> selectAttr_box;
    private javax.swing.JLabel selectAttr_text;
    private javax.swing.JComboBox<String> selectItemType_box;
    private javax.swing.JComboBox<String> selectItemType_box_display;
    private javax.swing.JLabel selectItemType_text;
    private javax.swing.JLabel selectItemType_text_display;
    // End of variables declaration//GEN-END:variables
}
